auth:
  user: 'admin'
  pass: 'superpassword'
  
server:
  port: 1337

redis:
  url: 'redis://127.0.0.1:6379/bk2riak' # The url must be of the form redis://<host>:<port>/<database_name>
  namespace: 'bitcask2riak'

riak:
  :nodes:
    - :host: '127.0.0.1'
      :http_port: '8098'
      :pb_port: '8087'
    - :host: '127.0.0.1'
      :http_port: '18098'
      :pb_port: '18087'
    - :host: '127.0.0.1'
      :http_port: '28098'
      :pb_port: '28087'
  :protocol: pbc
  
limits:
  threshold: 100000 # Wait for the Sidekiq queue to be < threshold so that we don't overload redis
  sleep: 60 # Time to sleep until retrying to queue new jobs in Sidekiq if number of enqueued jobs in Sidekiq >= threshold